---
services:
  backend:
    build: ./backend
    env_file:
      - .env
    volumes:
      - ./dialogflow-credentials.json:/app/config/dialogflow-credentials.json:ro
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=api/app.py
      - FLASK_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
